In [49]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Convolution2D
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.layers import Flatten
from keras.utils import np_utils
from sklearn.metrics import accuracy_score

In [50]:
from keras.datasets import mnist 

In [21]:
(x_train,y_train),(x_test,y_test)=mnist.load_data()

In [22]:
y_test

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [23]:
x_train.shape

(60000, 28, 28)

In [24]:
y_train.shape

(60000,)

In [25]:
x_test.shape

(10000, 28, 28)

In [26]:
y_test.shape

(10000,)

In [51]:
x_train = x_train.reshape(x_train.shape[0], 28, 28, 1)
x_test = x_test.reshape(x_test.shape[0], 28, 28, 1)
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')

In [52]:
x_train /= 255
x_test /= 255

In [53]:
n_classes = 10

In [30]:
y_train = np_utils.to_categorical(y_train, n_classes)
y_test = np_utils.to_categorical(y_test, n_classes)

In [31]:
y_train.shape

(60000, 10)

In [32]:
y_test.shape

(10000, 10)

In [33]:
y_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.]], dtype=float32)

In [34]:
y_test

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [35]:
x_train

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [36]:
x_test

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [42]:
model = Sequential()
model.add(Convolution2D(25, kernel_size=(3,3), strides=(1,1), padding='valid', activation='relu', input_shape=(28,28,1)))
model.add(MaxPooling2D(pool_size=(1,1)))
model.add(Flatten())


In [43]:
model.add(Dense(100, activation='relu',kernel_initializer="uniform"))
model.add(Dense(10, activation='softmax',kernel_initializer="uniform"))

In [54]:
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')

In [55]:
model.fit(x_train, y_train, batch_size=128, epochs=10, validation_data=(x_test, y_test))

Epoch 1/10
469/469 [==============================] - 50s 104ms/step - loss: 1.7674 - accuracy: 0.4165 - val_loss: 0.4486 - val_accuracy: 0.8742
Epoch 2/10
469/469 [==============================] - 50s 107ms/step - loss: 0.4173 - accuracy: 0.8796 - val_loss: 0.3273 - val_accuracy: 0.9033
Epoch 3/10
469/469 [==============================] - 47s 101ms/step - loss: 0.3322 - accuracy: 0.9030 - val_loss: 0.2860 - val_accuracy: 0.9167
Epoch 4/10
469/469 [==============================] - 44s 93ms/step - loss: 0.2834 - accuracy: 0.9168 - val_loss: 0.2454 - val_accuracy: 0.9280
Epoch 5/10
469/469 [==============================] - 47s 99ms/step - loss: 0.2475 - accuracy: 0.9280 - val_loss: 0.2191 - val_accuracy: 0.9363
Epoch 6/10
469/469 [==============================] - 50s 108ms/step - loss: 0.2261 - accuracy: 0.9342 - val_loss: 0.1972 - val_accuracy: 0.9420
Epoch 7/10
469/469 [==============================] - 45s 95ms/step - loss: 0.1951 - accuracy: 0.9445 - val_loss: 0.1799 - val_accur

In [56]:
model.save("mnist.h5")

In [57]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 26, 26, 25)        250       
_________________________________________________________________
max_pooling2d_1 (MaxPooling2 (None, 26, 26, 25)        0         
_________________________________________________________________
flatten (Flatten)            (None, 16900)             0         
_________________________________________________________________
dense (Dense)                (None, 100)               1690100   
_________________________________________________________________
dense_1 (Dense)              (None, 10)                1010      
Total params: 1,691,360
Trainable params: 1,691,360
Non-trainable params: 0
_________________________________________________________________
